"""first migration

Revision ID: 05353d232365
Revises: 
Create Date: 2019-05-21 21:07:37.520095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05353d232365'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completed_tasks_l',
    sa.Column('completed_id', sa.Integer(), nullable=False),
    sa.Column('task_desc', sa.String(length=250), nullable=True),
    sa.Column('complete_dtm', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('completed_id')
    )
    op.create_table('tasks_l',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('task_desc', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks_l')
    op.drop_table('completed_tasks_l')
    # ### end Alembic commands ###
